/*
#  AUTHORS:     Srizan Gangol
#  COURSE:      CSCE 4110
#  ASSIGNMENT:  Assignment #2
#  DESCRIPTION: Finding the length of LCS of 2 Protein Strings [Dynamic Programming]
#
#  Usuage:
#  $ g++ lcs.c -o lcs
#  $ ./lcs
#  WELCOME TO PROTEIN LCS ANALYSIS
# -------------------------
# > Press '1' to Find LCS
# > Press '0' to Exit
# $ CSCE4110>1
# ..
# .
*/

#include<iostream>
#include<cstring>
#include<cstdlib>
using namespace std;
// Function to impmlement LCS
void lcs( char *X, char *Y, int m, int n );

void manual();

void hardcode();
// Main Function that accepts INPUT & Executes lcs function

int main()
{
  int input;
  do{
    cout << "\n\n WELCOME TO PROTEIN LCS ANALYSIS\n";
    cout << "-----------------------------------\n";
    cout << "> Press '1' to Find LCS [Manual]\n";
    cout << "> Press '2' to Find LCS from DB\n";
    cout << "> Any other key to EXIT\n";
    cout << "$ CSCE4110>";
    cin >> input;
    if (input ==1){
      manual();
    }
    if (input ==2)
    {
      hardcode();
    }
    else break;
  } while (input==1|input==2);
  return 0;
}


void lcs( char *X, char *Y, int m, int n )
{
   int L[m+1][n+1];

   // Building L[m+1][n+1] bottom up
   // L[i][j] contains length of LCS of X[0..i-1] and Y[0..j-1]
   for (int i=0; i<=m; i++)
   {
     for (int j=0; j<=n; j++)
     {
       if (i == 0 || j == 0)
         L[i][j] = 0;
       else if (X[i-1] == Y[j-1])
         L[i][j] = L[i-1][j-1] + 1;
       else
         L[i][j] = max(L[i-1][j], L[i][j-1]);
     }
   }

   // Array for LCS
   int index = L[m][n];

   // Array to store LCS String
   char lcs[index+1];
   lcs[index] = '\0';

   // Bottom Up
   int i = m, j = n;
   while (i > 0 && j > 0)
   {

      if (X[i-1] == Y[j-1])
      {
          lcs[index-1] = X[i-1];
          i--; j--; index--;
      }

      else if (L[i-1][j] > L[i][j-1])
         i--;
      else
         j--;
   }

   // Final Output
  //  cout << "> LCS is: " << lcs << "\n";
   cout << "> LCS length =  " << strlen(lcs)<< "\n";
}

void manual()
{

  char X[1000];
  char Y[1000];

  cout << "Input Protein 1: " ;
  cin >> X;
  // cout << X;
  cout << "Input Protein 2: ";
  cin >> Y;
  // cout << Y;

  int m = strlen(X);
  int n = strlen(Y);
  lcs(X, Y, m, n);

}

void hardcode(){
  string protein[16];

  protein [0]= "MEASRCRLSPSGDSVFHEEMMKMRQAKLDYQRLLLEKRQRKKRLEPFMVQPNPEARLRRAKPRASDEQTPLVNCHTPHSNVILHGIDGPAAVLKPDEVHAPSVSSSVVEEDAENTVDTASKPGLQERLQKHDISESVNFDEETDGISQSACLERPNSASSQNSTDTGTSGSATAAQPADNLLGDIDDLEDFVYSPAPQGVTVRCRIIRDKRGMDRGLFPTYYMYLEKEENQKIFLLAARKRKKSKTANYLISIDPVDLSREGESYVGKLRSNLMGTKFTVYDRGICPMKGRGLVGAAHTRQELAAISYETNVLGFKGPRKMSVIIPGMTLNHKQIPYQPQNNHDSLLSRWQNRTMENLVELHNKAPVWNSDTQSYVLNFRGRVTQASVKNFQIVHKNDPDYIVMQFGRVADDVFTLDYNYPLCAVQAFGIGLSSFDSKLACE";
  protein [1]= "MEAARCAPGPRGDSAFDDETLRLRQLKLDNQRALLEKKQRKKRLEPLMVQPNPEARLRRLKPRGSEEHTPLVDPQMPRSDVILHGIDGPAAFLKPEAQDLESKPQVLSVGSPAPEEGTEGSADGESPEETAPKPDLQEILQKHGILSSVNYDEEPDKEEDEGGNLSSPSARSEESAAASQKAASETGASGVTAQQGDAQLGEVENLEDFAYSPAPRGVTVKCKVTRDKKGMDRGLFPTYYMHLEREENRKIFLLAGRKRKKSKTSNYLVSTDPTDLSREGESYIGKLRSNLMGTKFTVYDHGVNPVKAQGLVEKAHTRQELAAICYETNVLGFKGPRKMSVIIPGMNMNHERIPFRPRNEHESLLSKWQNKSMENLIELHNKAPVWNDDTQSYVLNFHGRVTQASVKNFQIVHGNDPDYIVMQFGRVADDVFTLDYNYPLCALQAFAIGLSSFDSKLACE";
  protein [2]= "MEGARSRCVLSGGSIFEDEGMKLRQLKLENQRALLEKKQKKKRLDPLMVQPNPEAKLHRSKPKGFEEQTPLVETPTTFHSAVVLHGIDRPVSFLKSEVQDLGNKLQTFSVGSSITAENADEENNGHVLTETLRNAHLQEILQKRGISGSLNFDEEDTEEEEEVSKRPASQSPHPESERPSSATIKKSFAEIGASCSPSHQTVAHLGEVENLEEFALRPAPHGITVKCRITRDKKGMDRGLFPTYYMHLEKDNNRKMFLLAGRKRKKSKTSNYIISVDPTDLSREGESFIGKLRSNLMGTKFTVYDHGVSPIKAQGEVEKAHTRQELAAVYYETNVLGFKGPRKMSVIIPGMNMHHKRIPVQPRNPENESLLSKWQTKDLENLIELHNKAPVWNDDTQSYVLNFHGRVTQASVKNFQIVHDNDPDYIVMQFGRVAEDVFTLDYNYPLCALQAFAIGLSSFDSKLACE";
  protein [3]= "MERTGERSGGTSMFEDESARLRHLKLENQRTLLEQKQRKKRQEILMVQSNRDTRQRRPKSGKCEEQAPLVQSQKQKSVNCNVILNGIDGPAAFLDSGFHELDSKIQVLTVGESCTDTDFNVGTGWPSCNEGRASPCNSERRGTPVSDEENTQPLNSIGRSNLEKTQQNSNRQEILRKPDVSKRDLQELLQERGISDSLNFDEDISDDDDGDDDDEACNASTRPASASSKKSLTETGTAEAVPPDPSGDIGEIGDLKEFALRPAPRGVVIKTRISRDKKGMDRGLYPTYYMHLERDNNRKVFLLAGRKRKRSKTSNYLISIDPTDLSREGGNFIGKLRSNLMGTKFTIYDNGESPAKVQGHMSNPTTRQEMAAVCYETNVLGFKGPRKMTVLIPGMNLNHERIPFQPQNDSESLLSRWGNKCQENIIELHNKAPVWNDDTQSYVLNFHGRVTHASVKNFQIVHDNDPDYIVMQFGRVAEDFFTLDYSYPLCALQAFSVALSSFDSKLACE";
  protein [4]= "MKLRQLKLDNQRALLEKKQRKKRLEPLMVQPNPEARLRRSKPRGSEEQTPLVEPHTPQNEVILHGIDGPAAFLKPDAQDLETKLHVVSVDSSAVEEDTEGSVDGEGTLDTVSKPDLQEILQKHGISGSLNFDEEETDGEEEGKKLCHSPYSVAERPNSASSQKSTTDTGASGSASQQTDNQLGEVENLEDFAYSPAPRGITVKCRITRDKKGMDRGLFPTYYMHLEKDENRKIFLLAGRKRKKSKTSNYLISTDPTDLSREGESYIGKLRSNLMGTKFTVYDHGVSPTKAQGLVEKAYVRQELAAICYETNVLGFKGPRKMSVIIPGMNMNHERIPFQPRNDHESLLSKWQNKTMENLIELHNKAPVWNDDTQSYVLNFHGRVTQASVKNFQIVHDNDPDYIVMQFGRVADDVFTLDYNYPLCALQAFAIGLSSFDSKLACE";
  protein [5]= "MEASRCRLSPSGDSVFHEEMMKMRQAKLDYQRLLLEKRQRKKRLEPFMVQPNPEARLRRAKPRASDEQTPLVNCHTPHSNVILHGIDGPAAVLKPDEVHAPSVSSPVVEEDAENTVDTASKPGLQERLQKHDISESVNFDEETDGISQSACLERPNSASSQNSTDTGTSGSATAAQPADNLLGDIDDLEDFVYSPAPQGVTVRCRIIRDKRGMDRGLFPTYYMYLEKEENQKIFLLAARKRKKSKTANYLISIDPVDLSREGESYVGKLR";
  protein [6]= "MESSLRRPGPRGDRSGAMAAGGDPRGPWSAFEDETMKLRQLKLDNQRALLEKKQRKKRLEPLMVQPNLEARPLRARPRGREEHALLVEPQAPQGGVILQGIDGPAAFLKPDAQDVDTRLHVLTVGSAATEDAEGSADGESARDPASKPDLQEVLRKHGISGSLNFDEEETDGEEGEGNQLRSQSPCSEAERPGSASSQKPAPGTGASGTASPHSDIQPGEIEDLEGFAYSPAPRGVTVKCRITRDKKGMDRGLFPTYYMHLEKDENRKIFLLAGRKRKKSKTSNYLISTDPTDLSREGESYIGKLRSNLMGTKFTVYDHGVSPAKAQGLVEKAYTRQELAAVCYETNVLGFKGPRKMSVIIPGMNMNHERIPFQPRNDHESLLPKWQNKAMENLIELHNKSPVWNDDTQSYVLNFHGRVTQASVKNFQIVHDNDPDYIVMQFGRVADDVFTLDYNYPLCALQAFAIGLSSFDSKLACE";
  protein [7]= "MEAARCAPGSRGDSAFEDETLRLRQLKLDNQRALLEKKQRKKRLEPLMVQPNPEARLRRLKPRGSEEHTPLVDPQTPCSDVILHGIDGPAAFLKPEAQDLESKPQVLSVGSSPTPEEGTEGSADGESPVETASKPDLQEILQKHGILSSVNYDEEPDEEAEDEGENLSSLPAQSEKESAGASQKAASDTGASGMTAQQGDAQLGEVENLEDFAYSPAPRGVTVKCRVTRDKKGMDRGLFPTYYMHLEKEENRKIFLLAGRKRKKSKTSNYLVSTDPTNLSREGESYIGKLRSNLMGTKFTVYDHGVNPVKAQGLVEKAHTRQELAAICYETNVLGFKGPRKMSVIIPGMNMNHERIPFRPRNEHESLLSKWQNKSMENLIELHNKAPVWNDDTQSYVLNFHGRVTQASVKNFQIVHGNDPDYIVMQFGRVADDVFTLDYNYPLCALQAFAIGLSSFDSKLACE";
  protein [8]= "MEASRCRLGPSGDSVFHEEMMKMRQAKLDYQRLLLEKRQRKKRLEPFMVQPNPEARLRRAKPRASDEQTPLVNCHTPHSNVILHGIDGPAAVLKPDEVRTPSVSSPALEEDENTVGTASKPGLQESLQKHDISESVNFDEETDGRSQSACLERPNSASSQNSTDTGTSCSATAAQPADNLLGDIDDLEDFVYSPAPQGVTVRCRIIRDKKGMDRGLFPTYYMYLEKEENQKIFLLAARKRKKSKTANYLISTDPVDLSREGESYVGKLRSNLMGTKFTVYDRGICPIKGRGLVGAAHARQELAAISYETNVLGFKGPRKMSVIIPGMTLNHKQIPYQPRNNHDSLLSRWQNKTMENLIELHNKAPVWNSDTQSYVLNFRGRVTQASVKNFQIVHKNDPDYIVMQFGRVADDVFTLDYNYPLCAVQAFGIGLSSFDKCIQTLRIRELCEPHCHHR";
  protein [9]= "FSSLEDDSLNLRQQKLEKQRALLEQKQRRKRQELLMVQPNPDGRPRRSRPRRSEEQAPLVETNISTASDIILDGTNILHISVHCFEKLLLKMLFKIKLMYTIFQNAHKCIDGPAALLGSEAPDLGSKIQVLSVSQTPQQPSPPVTEEPETDADTDTLLEPKTDIHTLLQRRGLSGSMNYDEASEDEDEDDEYEAEERSRSLSPNTESTRPASASSTKSTTECIPVGSPSAEGSSIEVDNLEEFVLRPAPQGVTVKCRISRDKKGMDRGLYPTYFMHLEREDGKKVFLLAGRKRKKSKTSNYLISVDATDLSREGESFIGKLRS";
  protein [10]= "MSGINSRNQKMEQQRQLMEAYIRQKRASPGMVQASDLQINRPMSGMRSNSRELHAYDGPMQFISSPQNPDQILTNGSPGGINPVAMNTSRNHSNNMRSLSTINQEADLIEEISSHELEDEESSPVTVIEQHQQSASHSANSTQSQKPRARQHSFSDNLDEDDYTNRNVAGAAPVRPAGMASSPYKDATLDGSSNGTGNGTGGESEGDVIGNIDQFVMQPAPQGVLYKCRITRDRKGMDRGLFPIYYLHLERDYGKKIFLLGGRKRKKSKTSNYIVSCDPTDLSRNADGFCGKLRSNVFGTSFTVFDNGNKESTESPRLDLAVIIYDTNILGFKGPRNMTVILPGMTEDDQRVKISSADPKQQGILDLWKMKNMDNIVELHNKTPVWNDETQSYVLNFHGRVTQASVKNFQLVHDSDPEYIVMQFGRTSEDVFTMDYRYPLCAMQAFAIALSSFDGKIACE";
  protein [11]= "MTDTNSQWIEMNLQRQRKMLEDKQKQKRHQSAGSVRTTSTAMSMNSMKDYPTFDNSLPFSISDNSSVSVSMNTPLIPTQDPIAQPRMQSMPRQQPQQVQESLISIGDYPDNDINAKLSKVNLTSCVVSDDEDEDKRSYADSPWNTDVVADRIPSEVLPDYNFIKNNLAKFVEDPAVEHCLYKCSITRQKSGVDKGMFPTYFLHLEEFDTDKRQKIFLLAARKRKKSTTANYLLSTDPTNLSREGEGYCAKVRSNALGTQFTVYDSGQNPKKTTNHAAIRQELAAVIYETNVLGFKGPRKMTIVMPGIEPPTENRPAVRCPVRPIQDKHTLLERYRLNDLDSLKILSNKSPQWNDETQSYVLNFHGRVTQASVKNFQIIHQSSPEYIVMQFGRISDDEFTMDFRYPLSAVQAFGIAMTSFHGKLACE";
  protein [12]= "MPLSRSLLSRRISNSFRFHQGETTTAPESESIPPPSNMAGSSSWSAMLPELLGEIIRRVEETEDRWPQRRDVVTCACVSKKWREITHDFARSSLNSGKITFPSCLKLPGPRDFSNQCLIKRNKKTSTFYLYLALTPSFTDKGKFLLAARRFRTGAYTEYIISLDADDFSQGSNAYVGKLRSDFLGTNFTVYDSQPPHNGAKPSNGKASRRFASKQISPQVPAGNFEVGHVSYKFNLLKSRGPRRMVSTLRCPSPSPSSSSAGLSSDQKPCDVTKIMKKPNKDGSSLTILKNKAPRWHEHLQCWCLNFHGRVTVASVKNFQLVATVDQSQPSGKGDEETVLLQFGKVGDDTFTMDYRQPLSAFQAFAICLTSFGTKLACE";
  protein [13]= "MSFRGIVQDLRDGFGSLSRRSFDFRLSSLHKGKAQGSSFREYSSSRDLLSPVIVQTSRWANLPPELLFDVIKRLEESESNWPARKHVVACASVCRSWRAMCQEIVLGPEICGKLTFPVSLKQPGPRDAMIQCFIKRDKSKLTFHLFLCLSPALLVENGKFLLSAKRTRRTTRTEYIISMDADNISRSSNSYLGKLRSNFLGTKFLVYDTQPPPNTSSSALITDRTSRSRFHSRRVSPKVPSGSYNIAQITYELNVLGTRGPRRMHCIMNSIPISSLEPGGSVPNQPEKLVPAPYSLDDSFRSNISFSKSSFDHRSLDFSSSRFSEMGISCDDNEEEASFRPLILKNKQPRWHEQLQCWCLNFRGRVTVASVKNFQLVAARQPQPQGTGAAAAPTSAPAHPEQDKVILQFGKVGKDMFTMDYRYPLSAFQAFAICLSSFDTKLACE";
  protein [14]= "MSFLSIVRDVRDTVGSFSRRSFDVRVSNGTTHQRSKSHGVEAHIEDLIVIKNTRWANLPAALLRDVMKKLDESESTWPARKQVVACAGVCKTWRLMCKDIVKSPEFSGKLTFPVSLKQPGPRDGIIQCYIKRDKSNMTYHLYLSLSPAILVESGKFLLSAKRSRRATYTEYVISMDADNISRSSSTYIGKLKSNFLGTKFIVYDTAPAYNSSQILSPPNRSRSFNSKKVSPKVPSGSYNIAQVTYELNLLGTRGPRRMNCIMHSIPSLALEPGGTVPSQPEFLQRSLDESFRSIGSSKIVNHSGDFTRPKEEEGKVRPLVLKTKPPRWLQPLRCWCLNFKGRVTVASVKNFQLMSAATVQPGSGSDGGALATRPSLSPQQPEQSNHDKIILHFGKVGKDMFTMDYRYPLSAFQAFAISLSTFDTKLACE";
  protein [15]= "MSLKSILRDLKEVRDGLGGISKRSWSKSSHIAPDQTTPPLDNIPQSPWASLPPELLHDIIWRVEESETAWPARAAVVSCASVCKSWRGITMEIVRIPEQCGKLTFPISLKQPGPRDSPIQCFIKRNRATATYILYYGLMPSETENDKLLLAARRIRRATCTDFIISLSAKNFSRSSSTYVGKLRSGFLGTKFTIYDNQTASSTAQAQPNRRLHPKQAAPKLPTNSSTVGNITYELNVLRTRGPRRMHCAMDSIPLSSVIAEPSVVQGIEEEVSSSPSPKGETITTDKEIPDNSPSLRDQPLVLKNKSPRWHEQLQCWCLNFKGRVTVASVKNFQLVAEIDASLDAPPEEHERVILQFGKIGKDIFTMDYRYPLSAFQAFAICISSFDTKPACEG";

  for (int i=0; i<16;i++)
  {
    char A[1000];
    strcpy(A,protein[i].c_str());

    for(int j=(i+1);j<16;j++)
    {
      char B[1000];
      strcpy(B,protein[j].c_str());
      int m = strlen(A);
      int n = strlen(B);
      cout << i << " & " << j << "\n";
      lcs(A, B, m, n);
    }
  }

}
